### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Ronnie08** [TIBCOSoftware/flogo-web#1385]
I run yarn start server ,it get an error, this is the log, any help? 

```
ronnie@RonniedeMacBook-Pro flogo-web % yarn start server
yarn run v1.22.19
$ ng serve server
Using ts-node version 8.6.2, typescript version 3.7.5

info: [08:49:11.785] Starting indexer DB at /Users/ronnie/Ronnie/code/doc/flogo/flogo-web/dist/local/db/indexer.db

info: [08:49:13.200] Registered resource plugin 'flow' (github.com/project-flogo/flow)

debug: [08:49:13.200] HookApplicator: Registering before hooks
debug: [08:49:13.200] HookApplicator: No hook for remove
debug: [08:49:13.200] HookApplicator: No hook for list
info: [08:49:13.201] Registered resource plugin 'stream' (github.com/project-flogo/stream)

debug: [08:49:13.201] HookApplicator: Registering before hooks

debug: [08:49:13.201] HookApplicator: No hook for remove
debug: [08:49:13.202] HookApplicator: No hook for list

info: [08:49:13.662] Exec command: flogo list in /Users/ronnie/Ronnie/code/doc/flogo/flogo-web/dist/local/engines/flogo-web

info: [08:49:13.672] run command: flogo list

error: [08:49:13.731] Cannot read properties of undefined (reading 'map')

TypeError: Cannot read properties of undefined (reading 'map')
    at parseContributionList (/Users/ronnie/Ronnie/code/doc/flogo/flogo-web/apps/server/src/modules/engine/commander/index.ts:89:30)
    at Object.getInitializedEngine (/Users/ronnie/Ronnie/code/doc/flogo/flogo-web/apps/server/src/modules/engine/registry.ts:52:3)
    at Object.boostrapEngine (/Users/ronnie/Ronnie/code/doc/flogo/flogo-web/apps/server/src/init/bootstrap-engine.ts:5:18)

```

**Comment by v613** [comment]
Hi @Ronnie08,
Did you solve your problem ?

Few days ago, one of my colleague faced same problem, and we found out that is related to flogo-cli.
In `logo-web/dist/local/engines/flogo-web/src/` somehow the file `imports.go` wasn't complete, and `flogo list` can't found any contributors.
So I send my `imports.go` to him, and the problem vanished 😄
